version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/mydatabase
      - DB_USER_NAME=myuser
      - DB_PASSWORD=secret
      - DB_DRIVER_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
    volumes:
      - .:/app
    working_dir: /app
    command: java -jar app.jar

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_USER=myuser 
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql # mysql 데이터 저장 위치
    restart: always # 컨테이너 재시작 설정
    networks:
      - app-network
networks:
  app-network:
    driver: bridge                                
volumes:
  mysql_data: # mysql 데이터 저장 위치
    driver: local